# Generated by Django 4.1.3 on 2022-11-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_entregas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
